language: python
env:
    - TOX_ENV=py27-1.7
    - TOX_ENV=py27-1.8
    - TOX_ENV=py27-master
    - TOX_ENV=py33-1.7
    - TOX_ENV=py33-1.8
    - TOX_ENV=py34-1.7
    - TOX_ENV=py34-1.8
    - TOX_ENV=py34-master
install:
  - pip install tox coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/671c49ab17abad8623f6
    on_success: change
    on_failure: always
    on_start: false
